CREATE DATABASE Pc_clinics
GO

USE Pc_clinics
GO

CREATE TABLE CLINICA(
    idClinica INT PRIMARY KEY IDENTITY,
	razaoSocial VARCHAR(399) NOT NULL,
	cnpj CHAR(14) NOT NULL UNIQUE,
	enderecoClinica VARCHAR(150) NOT NULL UNIQUE
);
GO

CREATE TABLE VETERINARIO(
    idVeterinario INT PRIMARY KEY IDENTITY,
	idClinica INT FOREIGN KEY REFERENCES CLINICA(idClinica),
	nomeVeterinario VARCHAR(100) NOT NULL,
	crmv CHAR(6) NOT NULL UNIQUE
);
GO

CREATE TABLE DONO(
    idDono INT PRIMARY KEY IDENTITY,
	nomeDono VARCHAR(100) NOT NULL
);
GO

CREATE TABLE TIPO_PET(
    idTipoPet INT PRIMARY KEY IDENTITY,
	descricaoTipo VARCHAR(20) NOT NULL
);
GO

CREATE TABLE RACA(
    idRaca INT PRIMARY KEY IDENTITY,
	idTipoPet INT FOREIGN KEY REFERENCES TIPO_PET(idTipoPet),
	nomeRaca VARCHAR(50) NOT NULL
);
GO

CREATE TABLE PETS(
    idPets INT PRIMARY KEY IDENTITY,
	idDono INT FOREIGN KEY REFERENCES DONO(idDono),
	idRaca INT FOREIGN KEY REFERENCES RACA(idRaca),
	nomePet VARCHAR(50) NOT NULL,
	dataNascimento DATE 
);
GO

CREATE TABLE ATENDIMENTOS(
    idAtendimento INT PRIMARY KEY IDENTITY,
	idVeterinario INT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario),
	idPets INT FOREIGN KEY REFERENCES PETS(idPets),
	descricaoAtendimento VARCHAR(500) NOT NULL,
	dataAtendimento DATE
);
GO