CREATE DATABASE LOCADORA_M;

USE LOCADORA_M;
GO

CREATE TABLE EMPRESAS (
     idEmpresas  INT PRIMARY KEY IDENTITY,
     nomeEmpresa VARCHAR(100) NOT NULL UNIQUE
);
GO

CREATE TABLE MARCA(
     idMarca INT PRIMARY KEY IDENTITY,
	 nomeMarca VARCHAR(100) UNIQUE
);
GO

CREATE TABLE MODELO (
      idModelo INT PRIMARY KEY IDENTITY,
	  idMarca INT FOREIGN KEY REFERENCES MARCA (idMarca),
	  descricaoModelo VARCHAR(3000) NOT NULL
);
GO

CREATE TABLE VEICULOS (
     idVeiculos INT PRIMARY KEY IDENTITY,
	 idModelo INT FOREIGN KEY REFERENCES MODELO (idModelo),
	 idEmpresa INT FOREIGN KEY REFERENCES EMPRESAS (idEmpresas),
	 placaVeiculo VARCHAR(7) NOT NULL
);
GO

CREATE TABLE CLIENTE (
     idCliente INT PRIMARY KEY IDENTITY,
	 nomeCliente VARCHAR(100) NOT NULL,
	 CPF VARCHAR(11) NOT NULL
); 

CREATE TABLE ALUGUEL (
     idAluguel INT PRIMARY KEY IDENTITY,
	 idCliente INT FOREIGN KEY REFERENCES CLIENTE (idCliente),
	 idVeiculos INT FOREIGN KEY REFERENCES VEICULOS (idVeiculos),
	 dataInicio DATE NOT NULL,
	 dataFim DATE NOT NULL,
);
