USE LOCADORA_M;
GO

SELECT * FROM EMPRESAS;
GO

SELECT * FROM MARCA;
GO

SELECT * FROM MODELO;
GO

SELECT * FROM VEICULOS;
GO

SELECT * FROM CLIENTE;
GO

SELECT * FROM ALUGUEL;
GO

SELECT valorAluguel, dataInicio, dataFim, nomeCliente, descricaoModelo, placaVeiculo, nomeEmpresa FROM ALUGUEL
LEFT JOIN CLIENTE
ON ALUGUEL.idCliente = CLIENTE.idCliente
LEFT JOIN VEICULOS
ON ALUGUEL.idVeiculos = VEICULOS.idVeiculos
LEFT JOIN MODELO
ON MODELO.idModelo = VEICULOS.idModelo
LEFT JOIN MARCA
ON MARCA.idMarca = MODELO.idMarca
LEFT JOIN EMPRESAS
ON EMPRESAS.idEmpresas = VEICULOS.idVeiculos

SELECT nomeMarca, descricaoModelo, placaVeiculo FROM VEICULOS
LEFT JOIN MODELO
ON MODELO.idModelo = VEICULOS.idModelo
LEFT JOIN MARCA
ON MARCA.idMarca = MODELO.idMarca